eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9092
  sessionTimeout: 30
spring:
  application:
    name: ribbon
# druid
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/cpd_test?useUnicode=true&amp;characterEncoding=UTF-8
  username: root
  password: root
  maxActive: 100
  initialSize: 10
  minIdle: 5
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 30000
  validationQuery: SELECT 1
feign:
  httpclient:
    enabled: true
