server:
  port: 8761
  contextPath: /
  undertow:
    accesslog:
      dir: /data/V2/zuul_test/springboot/access
      enabled: true
      io-threads: 4
      worker-threads: 32
      buffer-size: 1024
      buffers-per-region: 10
spring:
  application:
    name: eureka-server
# 安全认证的配置  （测试ok，暂时enabled false,生产可以设置为true）暂时测试Spring http权限认证，由于此类认证算法可逆，安全性无法保证，所以暂时使用在eureka注册中心，其它的认证后续考虑替换成其它认证方式
security:  
  basic:  
    enabled: true
  user:  
    name: lyj # 用户名  
    password: 1989  # 用户密码  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false